development:
  adapter: postgresql
  database: flights1percent_development
  encoding: utf-8
  host: 127.0.0.1
production:
  adapter: postgresql
  database: flights1percent_production
  encoding: utf-8
  host: 127.0.0.1
